import { createHmac, scrypt, timingSafeEqual } from "node:crypto";

/**
 * The single-user credential check: a password you know plus a code from your
 * phone. Node-only — `proxy.ts` never calls into here.
 *
 * There is no user table. One password hash, one TOTP secret, both in
 * environment variables, generated by `scripts/gen-credentials.mjs`. Adding a
 * database of one row would add an attack surface and buy nothing.
 */

/** Must match the parameters in scripts/gen-credentials.mjs. */
const SCRYPT = { N: 32768, r: 8, p: 1, keylen: 64, maxmem: 128 * 1024 * 1024 } as const;

const TOTP_DIGITS = 6;
const TOTP_PERIOD_S = 30;
/** Accept one step either side — phones drift, and a 90-second window is not
 *  a meaningful weakening of a 6-digit code that also sits behind a password
 *  and a lockout. */
const TOTP_DRIFT_STEPS = 1;

export function authConfigured(): boolean {
  return Boolean(
    process.env.PRABALOS_PW_HASH &&
      process.env.PRABALOS_PW_SALT &&
      process.env.PRABALOS_TOTP_SECRET &&
      process.env.PRABALOS_SESSION_KEY,
  );
}

function scryptAsync(password: string, salt: Buffer): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    scrypt(password, salt, SCRYPT.keylen, SCRYPT, (err, key) =>
      err ? reject(err) : resolve(key as Buffer),
    );
  });
}

/**
 * Verifies the password. Always runs the full scrypt derivation, even when the
 * environment is misconfigured, so that a wrong password and a missing hash
 * take indistinguishable time.
 */
export async function verifyPassword(password: string): Promise<boolean> {
  const saltHex = process.env.PRABALOS_PW_SALT ?? "";
  const hashHex = process.env.PRABALOS_PW_HASH ?? "";
  const salt = Buffer.from(saltHex || "00".repeat(32), "hex");

  const derived = await scryptAsync(password, salt);
  if (!hashHex) return false;

  const expected = Buffer.from(hashHex, "hex");
  if (expected.length !== derived.length) return false;
  return timingSafeEqual(derived, expected);
}

/** RFC 4648 base32 decode, no padding, case-insensitive. */
function base32Decode(s: string): Buffer {
  const A = "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";
  const clean = s.toUpperCase().replace(/=+$/, "").replace(/\s+/g, "");
  let bits = 0;
  let value = 0;
  const out: number[] = [];
  for (const ch of clean) {
    const idx = A.indexOf(ch);
    if (idx === -1) throw new Error("bad base32");
    value = (value << 5) | idx;
    bits += 5;
    if (bits >= 8) {
      out.push((value >>> (bits - 8)) & 0xff);
      bits -= 8;
    }
  }
  return Buffer.from(out);
}

/** RFC 4226 dynamic truncation over an RFC 6238 time counter. */
function hotp(secret: Buffer, counter: number): string {
  const buf = Buffer.alloc(8);
  // Counter is well under 2^32 until the year 6000-odd; write the high word as
  // zero rather than pulling in BigInt.
  buf.writeUInt32BE(0, 0);
  buf.writeUInt32BE(counter >>> 0, 4);

  const digest = createHmac("sha1", secret).update(buf).digest();
  const offset = digest[digest.length - 1] & 0x0f;
  const code =
    ((digest[offset] & 0x7f) << 24) |
    ((digest[offset + 1] & 0xff) << 16) |
    ((digest[offset + 2] & 0xff) << 8) |
    (digest[offset + 3] & 0xff);
  return String(code % 10 ** TOTP_DIGITS).padStart(TOTP_DIGITS, "0");
}

/**
 * Verifies a TOTP code against the configured secret, accepting one step of
 * drift either side. Comparison is constant-time so the code cannot be
 * recovered digit by digit from response timing.
 */
export function verifyTotp(code: string, at: Date = new Date()): boolean {
  const secretB32 = process.env.PRABALOS_TOTP_SECRET ?? "";
  if (!secretB32) return false;

  const cleaned = code.replace(/\s+/g, "");
  if (!/^\d{6}$/.test(cleaned)) return false;

  let secret: Buffer;
  try {
    secret = base32Decode(secretB32);
  } catch {
    return false;
  }

  const counter = Math.floor(at.getTime() / 1000 / TOTP_PERIOD_S);
  const given = Buffer.from(cleaned, "utf8");
  let match = false;
  for (let d = -TOTP_DRIFT_STEPS; d <= TOTP_DRIFT_STEPS; d++) {
    const candidate = Buffer.from(hotp(secret, counter + d), "utf8");
    // No early exit: check every window so timing does not reveal which one hit.
    if (candidate.length === given.length && timingSafeEqual(candidate, given)) match = true;
  }
  return match;
}
